"""empty message

Revision ID: 8bbece38a60b
Revises: edb43f3d46f3
Create Date: 2024-12-05 14:58:46.624672

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8bbece38a60b'
down_revision = 'edb43f3d46f3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('portfolio_stocks', schema=None) as batch_op:
        batch_op.drop_constraint('portfolio_stocks_ticker_key', type_='unique')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('portfolio_stocks', schema=None) as batch_op:
        batch_op.create_unique_constraint('portfolio_stocks_ticker_key', ['ticker'])

    # ### end Alembic commands ###
