"""empty message

Revision ID: d30ffe8189ab
Revises: 9c57f23e362e
Create Date: 2024-12-08 12:03:05.202393

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd30ffe8189ab'
down_revision = '9c57f23e362e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('favorite_crypto', schema=None) as batch_op:
        batch_op.add_column(sa.Column('crypto_id', sa.String(length=20), nullable=False))

    with op.batch_alter_table('watched_crypto', schema=None) as batch_op:
        batch_op.add_column(sa.Column('crypto_id', sa.String(length=20), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('watched_crypto', schema=None) as batch_op:
        batch_op.drop_column('crypto_id')

    with op.batch_alter_table('favorite_crypto', schema=None) as batch_op:
        batch_op.drop_column('crypto_id')

    # ### end Alembic commands ###
