"""porfoliostock

Revision ID: edb43f3d46f3
Revises: 5bc0760514d0
Create Date: 2024-12-05 11:44:06.331442

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'edb43f3d46f3'
down_revision = '5bc0760514d0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('portfolio_stocks', schema=None) as batch_op:
        batch_op.add_column(sa.Column('number_of_shares', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('pps_at_purchase', sa.Float(), nullable=False))
        batch_op.create_unique_constraint(None, ['ticker'])
        batch_op.drop_column('amount_invested')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('portfolio_stocks', schema=None) as batch_op:
        batch_op.add_column(sa.Column('amount_invested', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False))
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('pps_at_purchase')
        batch_op.drop_column('number_of_shares')

    # ### end Alembic commands ###
