name: Build and deploy Python app to Azure Web App - KobraStocks

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python version
        uses: actions/setup-python@v1
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m venv venv
          source venv/bin/activate
          pip install -r Backend/requirements.txt

      - name: Zip files for deployment
        run: |
          cd Backend
          zip -r ../app.zip .
          cd ..

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v3
        with:
          name: app-artifact
          path: app.zip

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v3
        with:
          name: app-artifact

      - name: Unzip artifact for deployment
        run: unzip app.zip -d .

      - name: Login to Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZUREAPPSERVICE_CREDENTIALS }} # Updated to use the correct secret key

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'KobraStocks'
          slot-name: 'Production'
          package: './app.zip'

