# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy Node.js app to Azure Web App - KobraStocksFrontend

on:
  push:
    branches:
      - main
  workflow_dispatch:

env:
  AZURE_WEBAPP_NAME: 'Kobra-Stocks-Frontend' # Set this to your application's name
  AZURE_WEBAPP_PACKAGE_PATH: './client' # Path to your web app project
  NODE_VERSION: '20.x' # Node.js version to use

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: 'Checkout code'
        uses: actions/checkout@v4

      - name: 'Set up Node.js'
        uses: actions/setup-node@v3
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: 'Install dependencies and build'
        run: |
          npm install
          npm run build --if-present
        working-directory: ${{ env.AZURE_WEBAPP_PACKAGE_PATH }}

      - name: 'Zip artifact for deployment'
        run: zip -r release.zip ${{ env.AZURE_WEBAPP_PACKAGE_PATH }}

      - name: 'Upload artifact for deployment'
        uses: actions/upload-artifact@v3
        with:
          name: frontend-app
          path: release.zip

  deploy:
    runs-on: ubuntu-latest
    needs: build
    permissions:
      id-token: write
    steps:
      - name: 'Download artifact from build job'
        uses: actions/download-artifact@v3
        with:
          name: frontend-app

      - name: 'Unzip artifact for deployment'
        run: unzip release.zip

      - name: 'Login to Azure'
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_7025DC1FC0824404B99B38A60BE7CB78 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_85DD9FF58E5641C792D182B085658B05 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_FA8381D3CD8F4B8BA26B407EF95F86D2 }}
          
      - name: 'Deploy to Azure Web App'
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'Kobra-Stocks-Frontend'
          package: ./client

